### ISSUE TITLE
Jenkins plugin returns "KeyError: 'status'"

### ISSUE THREAD

**Issue by johntdyer** [opensourcehacker/sevabot#57]
I keep seeing this in the sevabot logs

``` logs
2013-09-25 14:11:30,872 - sevabot.frontend.api - INFO - Successfully sent message (sun) - https://jenkins.xxxxxxx.com/job/PhonoSDK-1.1-Mobile/158/

2013-09-25 14:11:31,154 - sevabot.frontend.api - ERROR - 'status'
2013-09-25 14:11:31,154 - sevabot.frontend.api - ERROR - 'status'
Traceback (most recent call last):
  File "/Users/administrator/opt/sevabot/sevabot/frontend/api.py", line 55, in dispatch_request
    msg = self.compose()
  File "/Users/administrator/opt/sevabot/sevabot/frontend/api.py", line 197, in compose
    if payload['build']['status'] == 'SUCCESS':
KeyError: 'status'
2013-09-25 14:11:34,674 - sevabot.frontend.api - INFO - Successfully sent message (sun) - https://jenkins.xxxxxx.com/job/PhonoSDK-1.0-Mobile/171/

```

I also ran wireshark on the machine to inspect the post, and the key is there.  So any idea why I am getting this log line indicating a problem when there isn't actually one ? 

Thanks!

-John

**Comment by ddimitriou** [comment]
Hi, the control above that line includes all payloads except COMPLETED. The STARTED payload does not contain status element.

**Comment by miohtama** [comment]
Sounds like a change in Jenkins API or oversight in the initial implementation. The solution would be a simple patch:

```
    if payload['build'].get('status') == 'SUCCESS';   # get() falls back to None if the element is not present
```

**Comment by ddimitriou** [comment]
Sure! That should do it! :)

**Comment by romanki** [comment]
could you please also resolve it for the next two lines also ? 

2014-09-25 08:58:54,227 - sevabot.frontend.api - ERROR - 'status'
Traceback (most recent call last):
  File "/home/skype/sevabot/sevabot/frontend/api.py", line 55, in dispatch_request
    msg = self.compose()
  File "/home/skype/sevabot/sevabot/frontend/api.py", line 199, in compose
    elif payload['build']['status'] == 'FAILURE':
KeyError: 'status'

Plus next one. 
looks like it should be changed to ".get('status')" in every line with messages.

**Comment by ddimitriou** [comment]
@romanki Yes you are right. I noticed it but, @miohtama has already merged the commit before I could change it.

**Comment by miohtama** [comment]
Please open a new pull request if this needs to changed.

**Comment by romanki** [comment]
Hi, 

created #87
