### ISSUE TITLE
python setup.py develop fails

### ISSUE THREAD

**Issue by craigco** [opensourcehacker/sevabot#71]
When installing sevabot on ubuntu 12.04, I have sevabot working:  responses in skype.  The website interface is not launching though.  On start up there is no description of a web endpoint at the ip address specified in settings.py.

After a clean reinstall, I notice that I get this output during python setup.py develop:

Finished processing dependencies for sevabot==1.2.5.dev0
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function

```
info('process shutting down')
```

TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function

```
info('process shutting down')
```

TypeError: 'NoneType' object is not callable

**Comment by miohtama** [comment]
Most likely a system-specfici issue, but this information is not enough to give clue what could be wrong.

**Comment by craigco** [comment]
I thought the same thing.  Here's a full dump of the error

Ubuntu 12.04
virtualenv 1.11.4
pip 1.5.4
setuptools 2.2
python 2.7.3

as skype user:
virtualenv venv (completes successfully)
. venv/bin/activate (now in virtual environment)
python setup.py develop
running develop
running egg_info
writing dependency_links to sevabot.egg-info/dependency_links.txt
writing requirements to sevabot.egg-info/requires.txt
writing sevabot.egg-info/PKG-INFO
writing top-level names to sevabot.egg-info/top_level.txt
writing entry points to sevabot.egg-info/entry_points.txt
reading manifest file 'sevabot.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'main_directory'
writing manifest file 'sevabot.egg-info/SOURCES.txt'
running build_ext
Creating /home/skype/sevabot/venv/lib/python2.7/site-packages/sevabot.egg-link (
link to .)
Adding sevabot 1.2.5.dev0 to easy-install.pth file
Installing sevabot script to /home/skype/sevabot/venv/bin

Installed /home/skype/sevabot
Processing dependencies for sevabot==1.2.5.dev0
Searching for plac
Reading https://pypi.python.org/simple/plac/
Best match: plac 0.9.1
Downloading https://pypi.python.org/packages/source/p/plac/plac-0.9.1.tar.gz#md5
=d7c90a689341c9a8f2706669f4be8b2b
Processing plac-0.9.1.tar.gz
Writing /tmp/easy_install-heOhMF/plac-0.9.1/setup.cfg
Running plac-0.9.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-heOhMF/pla
c-0.9.1/egg-dist-tmp-kKBtT1
Adding plac 0.9.1 to easy-install.pth file
Installing plac_runner.py script to /home/skype/sevabot/venv/bin

Installed /home/skype/sevabot/venv/lib/python2.7/site-packages/plac-0.9.1-py2.7.
egg
Searching for Skype4Py
Reading https://pypi.python.org/simple/Skype4Py/
Best match: Skype4Py 1.0.35
Downloading https://pypi.python.org/packages/source/S/Skype4Py/Skype4Py-1.0.35.z
ip#md5=e84a826fac4e5702c474d931160b4723
Processing Skype4Py-1.0.35.zip
Writing /tmp/easy_install-GOxfyM/Skype4Py-1.0.35/setup.cfg
Running Skype4Py-1.0.35/setup.py -q bdist_egg --dist-dir /tmp/easy_install-GOxfy
M/Skype4Py-1.0.35/egg-dist-tmp-Wb0iRf
warning: no previously-included files matching '*.pyc' found anywhere in distrib
ution
Adding Skype4Py 1.0.35 to easy-install.pth file

Installed /home/skype/sevabot/venv/lib/python2.7/site-packages/Skype4Py-1.0.35-p
y2.7.egg
Searching for Flask
Reading https://pypi.python.org/simple/Flask/
Best match: Flask 0.10.1
Downloading https://pypi.python.org/packages/source/F/Flask/Flask-0.10.1.tar.gz#
md5=378670fe456957eb3c27ddaef60b2b24
Processing Flask-0.10.1.tar.gz
Writing /tmp/easy_install-gLisTS/Flask-0.10.1/setup.cfg
Running Flask-0.10.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gLisTS/F
lask-0.10.1/egg-dist-tmp-rARvt0
warning: no files found matching '_' under directory 'tests'
warning: no previously-included files matching '_.pyc' found under directory 'do
cs'
warning: no previously-included files matching '_.pyo' found under directory 'do
cs'
warning: no previously-included files matching '_.pyc' found under directory 'te
sts'
warning: no previously-included files matching '_.pyo' found under directory 'te
sts'
warning: no previously-included files matching '_.pyc' found under directory 'ex
amples'
warning: no previously-included files matching '*.pyo' found under directory 'ex
amples'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/_themes/.git'
Adding Flask 0.10.1 to easy-install.pth file

Installed /home/skype/sevabot/venv/lib/python2.7/site-packages/Flask-0.10.1-py2.
7.egg
Searching for itsdangerous>=0.21
Reading https://pypi.python.org/simple/itsdangerous/
Best match: itsdangerous 0.23
Downloading https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-
0.23.tar.gz#md5=985e726eb76f18aca81e703f0a6c6efc
Processing itsdangerous-0.23.tar.gz
Writing /tmp/easy_install-d7ioQU/itsdangerous-0.23/setup.cfg
Running itsdangerous-0.23/setup.py -q bdist_egg --dist-dir /tmp/easy_install-d7i
oQU/itsdangerous-0.23/egg-dist-tmp-B9YCE3
warning: no previously-included files matching '*' found under directory 'docs/_
build'
Adding itsdangerous 0.23 to easy-install.pth file

Installed /home/skype/sevabot/venv/lib/python2.7/site-packages/itsdangerous-0.23
-py2.7.egg
Searching for Jinja2>=2.4
Reading https://pypi.python.org/simple/Jinja2/
Best match: Jinja2 2.7.2
Downloading https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.7.2.tar.gz
#md5=df1581455564e97010e38bc792012aa5
Processing Jinja2-2.7.2.tar.gz
Writing /tmp/easy_install-aCR1Ge/Jinja2-2.7.2/setup.cfg
Running Jinja2-2.7.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-aCR1Ge/J
inja2-2.7.2/egg-dist-tmp-WbShun
warning: no files found matching '_' under directory 'custom_fixers'
warning: no previously-included files matching '_' found under directory 'docs/_
build'
warning: no previously-included files matching '_.pyc' found under directory 'ji
nja2'
warning: no previously-included files matching '_.pyc' found under directory 'do
cs'
warning: no previously-included files matching '_.pyo' found under directory 'ji
nja2'
warning: no previously-included files matching '_.pyo' found under directory 'do
cs'
Adding Jinja2 2.7.2 to easy-install.pth file

Installed /home/skype/sevabot/venv/lib/python2.7/site-packages/Jinja2-2.7.2-py2.
7.egg
Searching for Werkzeug>=0.7
Reading https://pypi.python.org/simple/Werkzeug/
Best match: Werkzeug 0.9.4
Downloading https://pypi.python.org/packages/source/W/Werkzeug/Werkzeug-0.9.4.ta
r.gz#md5=670fad41f57c13b71a6816765765a3dd
Processing Werkzeug-0.9.4.tar.gz
Writing /tmp/easy_install-KzgfWC/Werkzeug-0.9.4/setup.cfg
Running Werkzeug-0.9.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-KzgfWC
/Werkzeug-0.9.4/egg-dist-tmp-Llx54f
warning: no files found matching '_' under directory 'werkzeug/debug/templates'
warning: no files found matching '_' under directory 'tests'
warning: no previously-included files matching '_.pyc' found under directory 'do
cs'
warning: no previously-included files matching '_.pyo' found under directory 'do
cs'
warning: no previously-included files matching '_.pyc' found under directory 'te
sts'
warning: no previously-included files matching '_.pyo' found under directory 'te
sts'
warning: no previously-included files matching '_.pyc' found under directory 'ex
amples'
warning: no previously-included files matching '_.pyo' found under directory 'ex
amples'
no previously-included directories found matching 'docs/_build'
Adding Werkzeug 0.9.4 to easy-install.pth file

Installed /home/skype/sevabot/venv/lib/python2.7/site-packages/Werkzeug-0.9.4-py
2.7.egg
Searching for markupsafe
Reading https://pypi.python.org/simple/markupsafe/
Best match: MarkupSafe 0.19
Downloading https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.19
.tar.gz#md5=ccb3f746c807c5500850987006854a6d
Processing MarkupSafe-0.19.tar.gz
Writing /tmp/easy_install-LMie5X/MarkupSafe-0.19/setup.cfg
Running MarkupSafe-0.19/setup.py -q bdist_egg --dist-dir /tmp/easy_install-LMie5
X/MarkupSafe-0.19/egg-dist-tmp-rAid5z
Adding MarkupSafe 0.19 to easy-install.pth file

Installed /home/skype/sevabot/venv/lib/python2.7/site-packages/MarkupSafe-0.19-p
y2.7-linux-x86_64.egg
Searching for setuptools==2.2
Best match: setuptools 2.2
Adding setuptools 2.2 to easy-install.pth file
Installing easy_install-3.4 script to /home/skype/sevabot/venv/bin
Installing easy_install script to /home/skype/sevabot/venv/bin

Using /home/skype/sevabot/venv/lib/python2.7/site-packages
Finished processing dependencies for sevabot==1.2.5.dev0
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function

```
info('process shutting down')
```

TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function

```
info('process shutting down')
```

TypeError: 'NoneType' object is not callable
