### ISSUE TITLE
Can't create Virtualenv

### ISSUE THREAD

**Issue by TheKinrar** [opensourcehacker/sevabot#77]
I followed this guide : https://sevabot-skype-bot.readthedocs.org/en/latest/ubuntu.html
When I type the command "python virtualenv.py venv", wich sould install Sevabot, I get this error :

```
skype@**********:~/sevabot$ python virtualenv.py venv
New python executable in venv/bin/python
Cannot find a wheel for setuptools
Cannot find a wheel for pip
Installing setuptools, pip...
  Complete output from command /home/skype/sevabot/venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pip
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "virtualenv.py", line 2338, in <module>
    main()
  File "virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "virtualenv.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "virtualenv.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/skype/sevabot/venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
```

I'm running Debian Wheezy 7.5.

**Comment by comentarinformal** [comment]
the installation docs seem to be outdated. You need to apt-get install python-virtualenv
Then, skip the "python virtualenv.py venv" step and just do "virtualenv venv".

**Comment by miohtama** [comment]
Thanks. Apparently virtualenv has changed, updated instructions for Ubuntu.
