### ISSUE TITLE
Skype 4.3+ is now required

### ISSUE THREAD

**Issue by Fumler** [opensourcehacker/sevabot#84]
Skype just killed everything below 4.3. So to be able to connect at all right now you need to update, which is not in apt-get atm.

http://askubuntu.com/questions/488053/how-to-install-skype-4-3

**Comment by grepjuice** [comment]
After upgrading I'm getting errors connecting to the API:

```
$ ./scripts/start-server.sh start
Xvfb already running
fluxbox already running
skype already running
2014-08-18 13:57:32,949 - sevabot - INFO - Starting sevabot
2014-08-18 13:57:32,953 - sevabot - INFO - Discovered module timeout: /home/skype/sevabot/modules/timeout.sh
2014-08-18 13:57:32,954 - sevabot - INFO - Discovered module memoryhog: /home/skype/sevabot/modules/memoryhog.sh
2014-08-18 13:57:32,954 - sevabot - INFO - Discovered module weather: /home/skype/sevabot/modules/weather.py
2014-08-18 13:57:32,954 - sevabot - INFO - Discovered module ping: /home/skype/sevabot/modules/ping.sh
2014-08-18 13:57:32,954 - sevabot - INFO - Discovered module soundcloud: /home/skype/sevabot/modules/soundcloud.rb
Started Sevabot web server process id 
2014-08-18 13:57:32,954 - sevabot - INFO - Discovered module ambush: /home/skype/sevabot/modules/ambush.sh
2014-08-18 13:57:32,954 - sevabot - INFO - Discovered module sad: /home/skype/sevabot/modules/sad.py
skype@devrec105:~/sevabot$ 2014-08-18 13:57:32,970 - sevabot - INFO - Skype API connection established
2014-08-18 13:57:32,988 - Skype4Py.api.posix_x11.SkypeAPI - INFO - opened
2014-08-18 13:57:33,007 - sevabot - DEBUG - Attaching to Skype
2014-08-18 13:57:33,007 - Skype4Py.api.posix_x11.SkypeAPI - INFO - thread started
Traceback (most recent call last):
  File "./scripts/../venv/bin/sevabot", line 8, in <module>
    load_entry_point('sevabot==1.1.dev0', 'console_scripts', 'sevabot')()
  File "/home/skype/sevabot/sevabot/frontend/main.py", line 163, in entry_point
    exit_code = plac.call(main)
  File "/home/skype/sevabot/venv/local/lib/python2.7/site-packages/plac-0.9.1-py2.7.egg/plac_core.py", line 309, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "/home/skype/sevabot/venv/local/lib/python2.7/site-packages/plac-0.9.1-py2.7.egg/plac_core.py", line 195, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/skype/sevabot/sevabot/frontend/main.py", line 113, in main
    sevabot.start()
  File "/home/skype/sevabot/sevabot/bot/bot.py", line 34, in start
    self.skype.Attach()
  File "build/bdist.linux-x86_64/egg/Skype4Py/skype.py", line 408, in Attach
  File "build/bdist.linux-x86_64/egg/Skype4Py/api/posix_x11.py", line 375, in attach
Skype4Py.errors.SkypeAPIError: Skype attach timeout
2014-08-18 13:58:03,140 - Skype4Py.api.posix_x11.SkypeAPI - INFO - thread finished
2014-08-18 13:58:03,147 - Skype4Py.api.posix_x11.SkypeAPI - INFO - closed
```

**Comment by miohtama** [comment]
Please see https://github.com/awahlig/skype4py/issues/34

**Comment by grepjuice** [comment]
That seems like they're able to make an API connection and have issues with chatrooms. I'm not able to get that far.

**Comment by miohtama** [comment]
@grepjuice Did the earlier version work (which) for you? 

I think it might be some general problem for you, not related to Skype update. But let's see if more error reports come in.

**Comment by grepjuice** [comment]
Yes worked previously on version 4.1.

**Comment by grepjuice** [comment]
After double checking the setup it looks like it was unrelated after all. Got it working, thanks.

**Comment by ngoduykhanh** [comment]
Hi @grepjuice ,

is skype 4.3 works for you?

I installed sevabot and skype 4.3, it worked for my first chat room one week ago but now it can not see any new chat room id.
