### ISSUE TITLE
hudson.model.ParameterValue.buildEnvironment

### ISSUE THREAD

**Issue by romanki** [opensourcehacker/sevabot#86]
Hi, 
looks like notifications not working with parametrized Jobs,
is it Sevabot issue? Or this issue should be resolved with notification plugin developers? 

Notifying endpoint 'HTTP:http://sevabotserver:5000/jenkins-notifier/9269f992491cdb01b9f81ad2ed1e3fc9/notifypass/'
ERROR: Failed to notify endpoint 'HTTP:http://sevabotserver:5000/jenkins-notifier/9269f992491cdb01b9f81ad2ed1e3fc9/notify/'
java.lang.NoSuchMethodError: hudson.model.ParameterValue.buildEnvironment(Lhudson/model/Run;Lhudson/EnvVars;)V
    at com.tikal.hudson.plugins.notification.Phase.buildJobState(Phase.java:100)
    at com.tikal.hudson.plugins.notification.Phase.handle(Phase.java:41)
    at com.tikal.hudson.plugins.notification.JobListener.onStarted(JobListener.java:31)
    at hudson.model.listeners.RunListener.fireStarted(RunListener.java:213)
    at hudson.model.Run.execute(Run.java:1661)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:230)
Failed to notify endpoint 'HTTP:http://sevabotserver:5000/jenkins-notifier/9269f992491cdb01b9f81ad2ed1e3fc9/notifypass/' - java.lang.NoSuchMethodError: hudson.model.ParameterValue.buildEnvironment(Lhudson/model/Run;Lhudson/EnvVars;)V

**Comment by moises-silva** [comment]
I'm seeing the same issue with Jenkins version 1.554

**Comment by moises-silva** [comment]
... and sorry to barge in, I am _not_ using Sevabot, so I suspect this is a Jenkins issue, probably nothing to do with Sevabot
