### ISSUE TITLE
Issue with topic of groups

### ISSUE THREAD

**Issue by tc0nn** [opensourcehacker/sevabot#92]
The topic of this group was "Web Release 3.x"
Any ideas why this would cause Errno 105?

Exception in thread Skype4Py MessageStatus event scheduler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/skype/sevabot/venv/local/lib/python2.7/site-packages/Skype4Py-1.0.35-py2.7.egg/Skype4Py/utils.py", line 225, in run
    handler(_self.args, *_self.kwargs)
  File "/home/skype/sevabot/sevabot/bot/bot.py", line 95, in handleMessages
    logger.debug("Incoming %s - %s - %s: %s" % (status, msg.Chat.FriendlyName,
  File "/home/skype/sevabot/venv/local/lib/python2.7/site-packages/Skype4Py-1.0.35-py2.7.egg/Skype4Py/chat.py", line 245, in _GetFriendlyName
    return self._Property('FRIENDLYNAME')
  File "/home/skype/sevabot/venv/local/lib/python2.7/site-packages/Skype4Py-1.0.35-py2.7.egg/Skype4Py/chat.py", line 33, in _Property
    return self._Owner._Property('CHAT', self.Name, PropName, Value, Cache)
  File "/home/skype/sevabot/venv/local/lib/python2.7/site-packages/Skype4Py-1.0.35-py2.7.egg/Skype4Py/skype.py", line 296, in _Property
    value = self._DoCommand('GET %s' % jarg, jarg)
  File "/home/skype/sevabot/venv/local/lib/python2.7/site-packages/Skype4Py-1.0.35-py2.7.egg/Skype4Py/skype.py", line 281, in _DoCommand
    raise SkypeError(int(errnum), errstr)
SkypeError: [Errno 105] Invalid chat name

**Comment by tc0nn** [comment]
Anyone?

**Comment by chrnola** [comment]
I think the fact that it was a group is the problem. I got the same error when attempting to join my bot to a group chat (did not have a topic defined).

**Comment by miohtama** [comment]
Please see https://github.com/awahlig/skype4py/issues/34

Microsoft has disabled API to join group chats.
