### ISSUE TITLE
Bot dont resolve some characters

### ISSUE THREAD

**Issue by gamelaster** [opensourcehacker/sevabot#95]
Heya,

i got this error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/Skype4Py/api/posix_x11.py", line 297, in run
    self.notify(data.decode('utf-8'))
  File "build/bdist.linux-x86_64/egg/Skype4Py/api/posix_x11.py", line 465, in notify
    self.notifier.notification_received(cmd)
  File "build/bdist.linux-x86_64/egg/Skype4Py/skype.py", line 151, in notification_received
    skype._CallEventHandler('ContactsFocused', str(value))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u30c4' in position 10: ordinal not in range(128)
```

My nickname contains a Japanese word ツ what maybe doing a trouble.. why?

**Comment by oysto** [comment]
Hi, this link might be of help to you: http://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

I was having the same problem, except with sending messages with japanese characters in them. I managed to get it solved by following the above link.

**Comment by gamelaster** [comment]
Dunno, the actual state, but probably will be good to close this issue.
